name: Nuclio Debug
description: 'GitHub action to deploy model with nuclio container'
author: 'Didi Ruhyadi'
# original-author: 'William Justin'

branding:
  icon: 'box'  
  color: 'red'

inputs:
  model-path:
    description: 'Model path'
    default: './model'
  model-name:
    description: 'Model name from function.yaml'
    required: true

outputs:
  status:
    description: "Container Status"
    value: ${{ steps.error.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Get nuctl
      run: |
        curl -s https://api.github.com/repos/nuclio/nuclio/releases/tags/1.5.16 \
          | grep -i "browser_download_url.*nuctl.*$(uname)" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -O nuctl -qi - && chmod +x nuctl
      shell: bash

    - name: Create Project
      run: ./nuctl create project cvat
      shell: bash

    - name: Deploy Model
      run: |
        ./nuctl deploy --project-name cvat --path ${{ inputs.model-path }} \
          --volume ${pwd}/common:/opt/nuclio/common \
          --platform local
      shell: bash

    - name: Get Function
      run: ./nuctl get function
      shell: bash

    - name: Logging Model Container
      uses: jwalton/gh-docker-logs@v1

    - name: Invoke Model
      run: |
        image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
        cat << EOF > /tmp/input.json
        {"image": "$image"}
        EOF
        cat /tmp/input.json | ./nuctl invoke ${{ inputs.model-name }} -c 'application/json'
      shell: bash