name: Nuclio Debug
description: 'GitHub action to deploy model with nuclio container'
author: 'Didi Ruhyadi'
# original-author: 'William Justin'

branding:
  icon: 'box'  
  color: 'red'

runs:
  using: "composite"
  steps:
    - name: Get nuctl
      run: |
        curl -s https://api.github.com/repos/nuclio/nuclio/releases/tags/1.5.16 \
          | grep -i "browser_download_url.*nuctl.*$(uname)" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -O nuctl -qi - && chmod +x nuctl
      shell: bash

    - name: Create project
      run: ./nuctl create project cvat
      shell: bash

    - name: Deploy Model
      run: |
        ./nuctl deploy --project-name cvat --path ./ \
          --volume ./common:/opt/nuclio/common \
          --platform local
      shell: bash

    - name: Get Function
      run: ./nuctl get function
      shell: bash