name: Nuclio Debug
description: 'GitHub action to deploy model with nuclio container'
author: 'Didi Ruhyadi'
# original-author: 'William Justin'

branding:
  icon: 'box'  
  color: 'red'

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: 'ruhyadi/nuclio-debug'
        ref: 'v1.7.1'
        path: '.'

    - name: Get nuctl
      run: |
        curl -s https://api.github.com/repos/nuclio/nuclio/releases/tags/1.5.16 \
          | grep -i "browser_download_url.*nuctl.*$(uname)" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -O nuctl -qi - && chmod +x nuctl
      shell: bash

    - name: Create Project
      run: ./nuctl create project cvat
      shell: bash

    - name: Deploy Model
      run: |
        ./nuctl deploy --project-name cvat --path ${pwd} \
          --volume ${pwd}/common:/opt/nuclio/common \
          --platform local
      shell: bash

    - name: Get Function
      run: ./nuctl get function
      shell: bash

    - name: Logging Model Container
      uses: jwalton/gh-docker-logs@v1
      # with:
      #   dest: './docker_logs'